puts "########################################################"
puts "# include_google_js plugin                             #"
puts "# Configuration                                        #"
puts "########################################################"
puts ""
puts "Add" 
puts "IncludeGoogleJs::Config.include_google_js = true"
puts "to environment.rb to use Google's copies of Prototype and Script.aculo.us."